
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 08 22:27:50 UYT 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MOD = 16;
  public static final int LONG = 4;
  public static final int PLUS = 10;
  public static final int INT_DIV = 15;
  public static final int TRUE = 7;
  public static final int ID = 2;
  public static final int EXP = 14;
  public static final int STRING = 6;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int FALSE = 8;
  public static final int MINUS = 11;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 3;
  public static final int MUL = 12;
}

