
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 02 20:17:57 UYT 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INTEGER = 3;
  public static final int ID = 2;
  public static final int DOUBLE = 6;
  public static final int LONG = 4;
  public static final int error = 1;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int ASSIGN = 7;
}

