
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 09 01:03:16 UYT 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MOD = 16;
  public static final int AND = 23;
  public static final int NOT_BIT = 20;
  public static final int LONG = 4;
  public static final int PLUS = 10;
  public static final int OR = 24;
  public static final int XOR_BIT = 19;
  public static final int LSHIFT_BIT = 21;
  public static final int NOT = 25;
  public static final int GREATEQUAL_THAN = 31;
  public static final int INT_DIV = 15;
  public static final int TRUE = 7;
  public static final int GREAT_THAN = 29;
  public static final int ID = 2;
  public static final int EXP = 14;
  public static final int LESSEQUAL_THAN = 30;
  public static final int EQUALS = 26;
  public static final int STRING = 6;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int LESS_THAN = 28;
  public static final int DIV = 13;
  public static final int RSHIFT_BIT = 22;
  public static final int FALSE = 8;
  public static final int MINUS = 11;
  public static final int PRINT = 32;
  public static final int NOT_EQUALS = 27;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 3;
  public static final int OR_BIT = 18;
  public static final int MUL = 12;
  public static final int AND_BIT = 17;
}

